# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code
name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Get version
      id: get_version
      run: echo ::set-output name=version::$(node -p "require('./package.json').version")

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: v${{ steps.get_version.outputs.version }}
        release_body: ${{ github.event.head_commit.message }}
        tag: v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: true


